// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.1";

// src/lib/mcp/tools/list-service-packages.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.1";
var packages = [
  {
    id: "minimum",
    name: "Minimum",
    description: "Lakis\xE4\xE4teinen ty\xF6terveyshuolto pienille yrityksille. Sis\xE4lt\xE4\xE4 lakis\xE4\xE4teisen dokumentaation, seurannan ja maksuttoman konsultaation.",
    features: [
      "Lakis\xE4\xE4teinen dokumentaatio",
      "Lakis\xE4\xE4teinen seuranta",
      "Kysy apua maksutta"
    ]
  },
  {
    id: "basic",
    name: "Basic",
    description: "Et\xE4palveluita alkuvaiheen yrityksen ty\xF6ntekij\xF6ille. Sis\xE4lt\xE4\xE4 kaikki Minimum-paketin palvelut sek\xE4 et\xE4vastaanotot.",
    features: [
      "Kaikki Minimum-paketin palvelut",
      "Et\xE4yhteys l\xE4\xE4k\xE4riin",
      "Et\xE4n\xE4 teht\xE4v\xE4 sairaanhoito"
    ]
  },
  {
    id: "support",
    name: "Support",
    description: "Kokonaisvaltaisempi ty\xF6terveyden tuki. Sis\xE4lt\xE4\xE4 Basic-paketin palvelut sek\xE4 l\xE4\xE4k\xE4rin l\xE4hivastaanotot ja tutkimukset.",
    features: [
      "Kaikki Basic-paketin palvelut",
      "L\xE4\xE4k\xE4rin vastaanotot",
      "Laboratoriokokeet ja kuvantamistutkimukset",
      "Psykologin ja fysioterapeutin vastaanotot"
    ]
  }
];
var list_service_packages_default = defineTool({
  name: "list_service_packages",
  title: "List StartHealth service packages",
  description: "List StartHealth's occupational health service packages (Minimum, Basic, Support) with features and descriptions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(packages, null, 2) }],
    structuredContent: { packages }
  })
});

// src/lib/mcp/tools/estimate-price.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z } from "npm:zod@^4.4.3";
function estimate(employees, founders, pkg) {
  const total = employees + founders;
  const perPerson = { minimum: 12, basic: 25, support: 45 }[pkg];
  const monthly = Math.round(total * perPerson);
  const netAfterKela = Math.round(monthly * 0.45);
  return { monthlyEuro: monthly, netAfterKelaEuro: netAfterKela };
}
var estimate_price_default = defineTool2({
  name: "estimate_price",
  title: "Estimate StartHealth monthly price",
  description: "Estimate the monthly occupational health price for a company. Intended for low-exposure industries. Not valid for restaurant, construction, machine shop, or night-shift work.",
  inputSchema: {
    employees: z.number().int().min(0).describe("Number of employees excluding founders."),
    founders: z.number().int().min(0).default(0).describe("Number of founders."),
    package: z.enum(["minimum", "basic", "support"]).describe("Service package."),
    riskIndustry: z.boolean().default(false).describe("True if the company has restaurant, construction, machine shop, or night-shift work.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ employees, founders, package: pkg, riskIndustry }) => {
    const total = employees + founders;
    if (riskIndustry) {
      return {
        content: [
          {
            type: "text",
            text: "Hintalaskuri ei anna arviota riskialoille (ravintola, rakennus, konepaja, y\xF6ty\xF6). Ota yhteytt\xE4 StartHealthiin yksil\xF6llist\xE4 tarjousta varten."
          }
        ],
        structuredContent: { riskIndustry: true }
      };
    }
    if (total < 1 || total > 50) {
      return {
        content: [
          {
            type: "text",
            text: "Hintalaskuri toimii 1\u201350 ty\xF6ntekij\xE4n yrityksille. Muille kokoluokille pyyd\xE4 tarjous."
          }
        ],
        structuredContent: { outOfRange: true, total }
      };
    }
    const result = estimate(employees, founders, pkg);
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: {
        ...result,
        currency: "EUR",
        vat: 0,
        note: "Suuntaa-antava arvio matala-altisteisille aloille. Kela-korvaus arvioitu 55 %."
      }
    };
  }
});

// src/lib/mcp/tools/list-articles.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z as z2 } from "npm:zod@^4.4.3";

// src/lib/mcp/articles.ts
var articles = [
  {
    "title": "Ty\xF6terveyspalvelun vaihtaminen \u2014 askel askeleelta -opas",
    "url": "/tyoterveys/vaihtaminen",
    "description": "Ty\xF6terveyspalvelun vaihtaminen: miksi ja milloin vaihtaa, mit\xE4 valmistella ja miten siirtym\xE4 sujuu ilman katkoja. Pk-yrityksen opas."
  }
];

// src/lib/mcp/tools/list-articles.ts
var list_articles_default = defineTool3({
  name: "list_articles",
  title: "List StartHealth articles",
  description: "List all StartHealth occupational-health guide articles. Optional keyword filter matches against title and description (case-insensitive).",
  inputSchema: {
    query: z2.string().optional().describe("Optional keyword filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const q = (query ?? "").toLowerCase().trim();
    const filtered = q ? articles.filter(
      (a) => a.title.toLowerCase().includes(q) || a.description.toLowerCase().includes(q) || a.url.toLowerCase().includes(q)
    ) : articles;
    const items = filtered.map((a) => ({
      title: a.title,
      url: `https://starthealth.fi${a.url}`,
      description: a.description
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { count: items.length, items }
    };
  }
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.1";
var get_contact_info_default = defineTool4({
  name: "get_contact_info",
  title: "Get StartHealth contact info",
  description: "Get contact and booking details for StartHealth (email, booking URL, website, service area).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      company: "StartHealth",
      website: "https://starthealth.fi",
      email: "jussikurikka@starthealth.fi",
      bookingUrl: "https://asiointi.starthealth.fi/",
      serviceArea: "Helsinki (paikan p\xE4\xE4ll\xE4) ja koko Suomi et\xE4vastaanotoin.",
      audience: "1\u2013200 hengen pk-yritykset ja startupit.",
      languages: ["fi", "en"]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "starthealth-mcp",
  title: "StartHealth MCP",
  version: "0.1.0",
  instructions: "Public tools for StartHealth, a modern occupational health provider for Finnish SMEs and startups. Use `list_service_packages` to see the Minimum/Basic/Support packages, `estimate_price` for a rough monthly price (low-exposure industries only), `list_articles` to browse Finnish occupational-health guides, and `get_contact_info` for contact and booking details.",
  tools: [list_service_packages_default, estimate_price_default, list_articles_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
