// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.1";

// src/lib/mcp/tools/list-service-packages.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.1";
var packages = [
  {
    id: "minimum",
    name: "Minimum",
    description: "Lakis\xE4\xE4teinen ty\xF6terveyshuolto pienille yrityksille. Sis\xE4lt\xE4\xE4 lakis\xE4\xE4teisen dokumentaation, seurannan ja maksuttoman konsultaation.",
    features: [
      "Lakis\xE4\xE4teinen dokumentaatio",
      "Lakis\xE4\xE4teinen seuranta",
      "Kysy apua maksutta"
    ]
  },
  {
    id: "basic",
    name: "Basic",
    description: "Et\xE4palveluita alkuvaiheen yrityksen ty\xF6ntekij\xF6ille. Sis\xE4lt\xE4\xE4 kaikki Minimum-paketin palvelut sek\xE4 et\xE4vastaanotot.",
    features: [
      "Kaikki Minimum-paketin palvelut",
      "Et\xE4yhteys l\xE4\xE4k\xE4riin",
      "Et\xE4n\xE4 teht\xE4v\xE4 sairaanhoito"
    ]
  },
  {
    id: "support",
    name: "Support",
    description: "Kokonaisvaltaisempi ty\xF6terveyden tuki. Sis\xE4lt\xE4\xE4 Basic-paketin palvelut sek\xE4 l\xE4\xE4k\xE4rin l\xE4hivastaanotot ja tutkimukset.",
    features: [
      "Kaikki Basic-paketin palvelut",
      "L\xE4\xE4k\xE4rin vastaanotot",
      "Laboratoriokokeet ja kuvantamistutkimukset",
      "Psykologin ja fysioterapeutin vastaanotot"
    ]
  }
];
var list_service_packages_default = defineTool({
  name: "list_service_packages",
  title: "List StartHealth service packages",
  description: "List StartHealth's occupational health service packages (Minimum, Basic, Support) with features and descriptions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(packages, null, 2) }],
    structuredContent: { packages }
  })
});

// src/lib/mcp/tools/estimate-price.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z } from "npm:zod@^4.4.3";
function estimate(employees, founders, pkg) {
  const total = employees + founders;
  const perPerson = { minimum: 12, basic: 25, support: 45 }[pkg];
  const monthly = Math.round(total * perPerson);
  const netAfterKela = Math.round(monthly * 0.45);
  return { monthlyEuro: monthly, netAfterKelaEuro: netAfterKela };
}
var estimate_price_default = defineTool2({
  name: "estimate_price",
  title: "Estimate StartHealth monthly price",
  description: "Estimate the monthly occupational health price for a company. Intended for low-exposure industries. Not valid for restaurant, construction, machine shop, or night-shift work.",
  inputSchema: {
    employees: z.number().int().min(0).describe("Number of employees excluding founders."),
    founders: z.number().int().min(0).default(0).describe("Number of founders."),
    package: z.enum(["minimum", "basic", "support"]).describe("Service package."),
    riskIndustry: z.boolean().default(false).describe("True if the company has restaurant, construction, machine shop, or night-shift work.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ employees, founders, package: pkg, riskIndustry }) => {
    const total = employees + founders;
    if (riskIndustry) {
      return {
        content: [
          {
            type: "text",
            text: "Hintalaskuri ei anna arviota riskialoille (ravintola, rakennus, konepaja, y\xF6ty\xF6). Ota yhteytt\xE4 StartHealthiin yksil\xF6llist\xE4 tarjousta varten."
          }
        ],
        structuredContent: { riskIndustry: true }
      };
    }
    if (total < 1 || total > 50) {
      return {
        content: [
          {
            type: "text",
            text: "Hintalaskuri toimii 1\u201350 ty\xF6ntekij\xE4n yrityksille. Muille kokoluokille pyyd\xE4 tarjous."
          }
        ],
        structuredContent: { outOfRange: true, total }
      };
    }
    const result = estimate(employees, founders, pkg);
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: {
        ...result,
        currency: "EUR",
        vat: 0,
        note: "Suuntaa-antava arvio matala-altisteisille aloille. Kela-korvaus arvioitu 55 %."
      }
    };
  }
});

// src/lib/mcp/tools/list-articles.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z as z2 } from "npm:zod@^4.4.3";

// src/lib/mcp/articles.ts
var articles = [
  {
    "title": "Ty\xF6terveys Helsinki \u2014 modernit ty\xF6terveyspalvelut helsinkil\xE4isille pk-yrityksille",
    "url": "/tyoterveys/helsinki",
    "description": "Ty\xF6terveys Helsinki kasvavalle yritykselle. Nopea aloitus, l\xE4pin\xE4kyv\xE4 hinta, digitaalinen vastaanotto + l\xE4hivastaanotto Helsingiss\xE4. Pyyd\xE4 tarjous."
  },
  {
    "title": "Ty\xF6terveys Espoo \u2014 moderni ty\xF6terveyshuolto espoolaisille yrityksille",
    "url": "/tyoterveys/espoo",
    "description": "Ty\xF6terveys Espoo kasvuyrityksille. Nopea aloitus, kiinte\xE4 kk-hinta, digitaalinen vastaanotto + l\xE4hivastaanotto Helsingiss\xE4. Pyyd\xE4 tarjous."
  },
  {
    "title": "Ty\xF6terveys Vantaa \u2014 k\xE4yt\xE4nn\xF6llinen ty\xF6terveyshuolto vantaalaisille yrityksille",
    "url": "/tyoterveys/vantaa",
    "description": "Ty\xF6terveys Vantaa yrityksille. Nopea aloitus, l\xE4pin\xE4kyv\xE4 hinta, digitaalinen vastaanotto + l\xE4hivastaanotto Helsingiss\xE4. Pyyd\xE4 tarjous."
  },
  {
    "title": "Ty\xF6terveys p\xE4\xE4kaupunkiseutu \u2014 vertailu, hinnat ja valintaopas",
    "url": "/tyoterveys/paakaupunkiseutu",
    "description": "Ty\xF6terveys p\xE4\xE4kaupunkiseudulla: vertaa Helsingin, Espoon ja Vantaan vaihtoehdot, hinnat ja toimijat. K\xE4yt\xE4nn\xF6llinen opas pk-yrityksille."
  },
  {
    "title": "Ty\xF6terveyshuolto pienyritykselle \u2014 miten aloitat ilman p\xE4\xE4nvaivaa",
    "url": "/tyoterveys/pienyritys",
    "description": "Ty\xF6terveyshuolto pienelle yritykselle: mit\xE4 sis\xE4ltyy, paljonko maksaa, miten aloitetaan. K\xE4yt\xE4nn\xF6n opas alle 50 hengen yrityksille."
  },
  {
    "title": "Startup-yrityksen ty\xF6terveys \u2014 7 asiaa, jotka perustajan kannattaa tiet\xE4\xE4",
    "url": "/tyoterveys/startup",
    "description": "Startup-yrityksen ty\xF6terveys: milloin aloittaa, paljonko maksaa, mit\xE4 sis\xE4ltyy ja miksi perinteinen ty\xF6terveys ei sovi startupille. K\xE4yt\xE4nn\xF6n opas."
  },
  {
    "title": "Ty\xF6terveys yritt\xE4j\xE4lle \u2014 kannattaako se ja paljonko se maksaa?",
    "url": "/tyoterveys/yrittajalle",
    "description": "Ty\xF6terveys yritt\xE4j\xE4lle: vapaaehtoinen mutta j\xE4rkev\xE4. Sis\xE4lt\xF6, hinta, Kela-korvaus, ja milloin yritt\xE4j\xE4 kuuluu ty\xF6terveyden piiriin."
  },
  {
    "title": "Digitaalinen ty\xF6terveys \u2014 miksi 80 % k\xE4ynneist\xE4 voi tehd\xE4 et\xE4n\xE4",
    "url": "/tyoterveys/digitaalinen",
    "description": "Digitaalinen ty\xF6terveys: chat, video, et\xE4resepti ja sairauslomat. Miksi 80 % k\xE4ynneist\xE4 ei vaadi l\xE4hivastaanottoa ja miten se muuttaa ty\xF6terveyden."
  },
  {
    "title": "Pienen yrityksen ty\xF6terveys \u2014 opas 1\u201320 hengen ty\xF6nantajalle",
    "url": "/tyoterveys/pieni-yritys",
    "description": "Pienen yrityksen ty\xF6terveys: konkreettinen opas alle 20 hengen yrityksen ty\xF6nantajalle. Hinta, sis\xE4lt\xF6, k\xE4ytt\xF6\xF6notto ja suurimmat sudenkuopat."
  },
  {
    "title": "Ty\xF6terveyspalveluiden vertailu 2026 \u2014 mik\xE4 sopii pk-yrityksellesi",
    "url": "/tyoterveys/vertailu",
    "description": "Ty\xF6terveyden vertailu 2026: Mehil\xE4inen, Terveystalo, Pihlajalinna, Heltti, Starthealth. Vahvuudet, heikkoudet ja sopivuus eri yrityskokoihin."
  },
  {
    "title": "Mit\xE4 ty\xF6terveyshuoltoon kuuluu \u2014 t\xE4ydellinen sis\xE4lt\xF6lista 2026",
    "url": "/tyoterveys/mita-kuuluu",
    "description": "Mit\xE4 ty\xF6terveyshuolto sis\xE4lt\xE4\xE4 2026: Kela 1 ja Kela 2 -tasot, terveystarkastukset, sairaanhoito, mielenhyvinvointi. T\xE4ydellinen sis\xE4lt\xF6lista."
  },
  {
    "title": "Onko ty\xF6terveys pakollinen \u2014 mit\xE4 laki sanoo ty\xF6nantajasta",
    "url": "/tyoterveys/pakollinen",
    "description": "Onko ty\xF6terveys pakollinen? Kyll\xE4 \u2014 ensimm\xE4isest\xE4 ty\xF6ntekij\xE4st\xE4 alkaen. Laki, Kela-korvaukset, sakot ja mit\xE4 pienen yrityksen kannattaa tiet\xE4\xE4."
  },
  {
    "title": "Kela-korvaus ty\xF6terveydest\xE4 \u2014 n\xE4in haet ja kuinka paljon saat",
    "url": "/tyoterveys/kela-korvaus",
    "description": "Kela-korvaus ty\xF6terveyshuollosta 2026: korvausprosentit, korvauskatot, hakuohjeet ja vinkit maksimaaliseen korvaukseen. K\xE4yt\xE4nn\xF6n opas ty\xF6nantajalle."
  },
  {
    "title": "Ty\xF6terveyssopimus \u2014 mit\xE4 sen pit\xE4\xE4 sis\xE4lt\xE4\xE4 ja mit\xE4 tarkistaa",
    "url": "/tyoterveys/sopimus",
    "description": "Ty\xF6terveyssopimus: mit\xE4 ty\xF6terveysmallin sopimus sis\xE4lt\xE4\xE4, keskeiset pyk\xE4l\xE4t, yleiset sudenkuopat ja tarkistuslista allekirjoitusta ennen."
  },
  {
    "title": "Ty\xF6terveyshuollon toimintasuunnitelma \u2014 malli ja sis\xE4lt\xF6 2026",
    "url": "/tyoterveys/toimintasuunnitelma",
    "description": "Ty\xF6terveyshuollon toimintasuunnitelma: mit\xE4 sen pit\xE4\xE4 sis\xE4lt\xE4\xE4, kuinka usein p\xE4ivitt\xE4\xE4 ja miksi se vaikuttaa Kela-korvaukseen. Malli ja tarkistuslista."
  },
  {
    "title": "Ty\xF6terveysl\xE4\xE4k\xE4ri \u2014 rooli, koulutus ja milloin ottaa yhteytt\xE4",
    "url": "/tyoterveys/laakari",
    "description": "Ty\xF6terveysl\xE4\xE4k\xE4ri: mit\xE4 h\xE4n tekee, mit\xE4 koulutusta vaaditaan, milloin ottaa yhteytt\xE4 ja miksi hyv\xE4n ty\xF6terveysl\xE4\xE4k\xE4rin l\xF6yt\xE4minen on t\xE4rke\xE4\xE4."
  },
  {
    "title": "Ty\xF6terveyshoitaja \u2014 teht\xE4v\xE4t, p\xE4tevyys ja rooli ty\xF6terveystiimiss\xE4",
    "url": "/tyoterveys/hoitaja",
    "description": "Ty\xF6terveyshoitaja: mit\xE4 h\xE4n tekee, millaista koulutusta vaaditaan ja miksi ty\xF6terveyshoitaja on usein tiimin t\xE4rkein yhteyshenkil\xF6."
  },
  {
    "title": "Ty\xF6terveys et\xE4n\xE4 \u2014 chat, video, s\xE4hk\xF6inen resepti",
    "url": "/tyoterveys/etana",
    "description": "Ty\xF6terveys et\xE4n\xE4: miten et\xE4vastaanotto toimii, mit\xE4 voi hoitaa et\xE4n\xE4, mit\xE4 ei, ja milloin et\xE4ty\xF6terveys on paras valinta yrityksellesi."
  },
  {
    "title": "Sairauspoissaolojen v\xE4hent\xE4minen \u2014 9 k\xE4yt\xE4nn\xF6n keinoa pk-yritykselle",
    "url": "/tyoterveys/sairauspoissaolot",
    "description": "Sairauspoissaolojen v\xE4hent\xE4minen: 9 konkreettista keinoa, jotka toimivat pk-yrityksess\xE4. Miten ty\xF6terveys auttaa, mit\xE4 esimies voi tehd\xE4."
  },
  {
    "title": "Ty\xF6hyvinvointi pienyrityksess\xE4 \u2014 konkreettinen opas ilman jargonia",
    "url": "/tyoterveys/tyohyvinvointi",
    "description": "Ty\xF6hyvinvointi pieness\xE4 yrityksess\xE4: mit\xE4 se tarkoittaa, miten sit\xE4 mitataan ja 10 k\xE4yt\xE4nn\xF6n toimenpidett\xE4, jotka toimivat pk-yrityksess\xE4."
  },
  {
    "title": "Ty\xF6kykyjohtaminen \u2014 mit\xE4 se on ja miten pk-yritys tekee sen oikein",
    "url": "/tyoterveys/tyokykyjohtaminen",
    "description": "Ty\xF6kykyjohtaminen pk-yrityksess\xE4: varhainen tuki, ty\xF6kykyneuvottelu, ammatillinen kuntoutus. Konkreettinen opas ilman HR-jargonia."
  },
  {
    "title": "Mielenterveys ty\xF6paikalla \u2014 mit\xE4 ty\xF6nantajan pit\xE4\xE4 tiet\xE4\xE4",
    "url": "/tyoterveys/mielenterveys",
    "description": "Mielenterveys ty\xF6paikalla: miten tukea, miten tunnistaa ongelmat varhain, miten ty\xF6terveys auttaa. K\xE4yt\xE4nn\xF6n opas pk-yrityksille."
  },
  {
    "title": "Burnout ty\xF6ss\xE4 \u2014 merkit, syyt ja toipuminen",
    "url": "/tyoterveys/burnout",
    "description": "Burnout ty\xF6ss\xE4: miten tunnistat merkit, miten ehk\xE4ist\xE4\xE4n ja miten toipuu. Opas ty\xF6ntekij\xF6ille ja esimiehille pk-yrityksess\xE4."
  },
  {
    "title": "Ty\xF6terveystarkastus \u2014 mit\xE4 se sis\xE4lt\xE4\xE4 ja milloin se tehd\xE4\xE4n",
    "url": "/tyoterveys/tarkastus",
    "description": "Ty\xF6terveystarkastus: mit\xE4 siihen kuuluu, kenelle se on, kuinka usein ja mik\xE4 on tarkoitus. Selke\xE4 opas pk-yrityksille."
  },
  {
    "title": "Mehil\xE4inen vs Terveystalo vs Pihlajalinna \u2014 vertailu ty\xF6terveyspalveluille",
    "url": "/tyoterveys/mehilainen-terveystalo",
    "description": "Mehil\xE4inen, Terveystalo ja Pihlajalinna ty\xF6terveyspalveluina: hinnat, palvelut, vahvuudet ja heikkoudet. Riippumaton vertailu pk-yritykselle."
  },
  {
    "title": "Miten valita ty\xF6terveyspalvelu \u2014 opas pk-yrityksen p\xE4\xE4tt\xE4j\xE4lle",
    "url": "/tyoterveys/miten-valita",
    "description": "Miten valita ty\xF6terveyspalvelu pk-yritykselle: 10 kriteeri\xE4, joita kannattaa arvioida, yleiset sudenkuopat ja k\xE4yt\xE4nn\xF6n checklist."
  },
  {
    "title": "Ty\xF6terveyspalvelun vaihtaminen \u2014 askel askeleelta -opas",
    "url": "/tyoterveys/vaihtaminen",
    "description": "Ty\xF6terveyspalvelun vaihtaminen: miksi ja milloin vaihtaa, mit\xE4 valmistella ja miten siirtym\xE4 sujuu ilman katkoja. Pk-yrityksen opas."
  }
];

// src/lib/mcp/tools/list-articles.ts
var list_articles_default = defineTool3({
  name: "list_articles",
  title: "List StartHealth articles",
  description: "List all StartHealth occupational-health guide articles. Optional keyword filter matches against title and description (case-insensitive).",
  inputSchema: {
    query: z2.string().optional().describe("Optional keyword filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const q = (query ?? "").toLowerCase().trim();
    const filtered = q ? articles.filter(
      (a) => a.title.toLowerCase().includes(q) || a.description.toLowerCase().includes(q) || a.url.toLowerCase().includes(q)
    ) : articles;
    const items = filtered.map((a) => ({
      title: a.title,
      url: `https://starthealth.fi${a.url}`,
      description: a.description
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { count: items.length, items }
    };
  }
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.1";
var get_contact_info_default = defineTool4({
  name: "get_contact_info",
  title: "Get StartHealth contact info",
  description: "Get contact and booking details for StartHealth (email, booking URL, website, service area).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      company: "StartHealth",
      website: "https://starthealth.fi",
      email: "jussikurikka@starthealth.fi",
      bookingUrl: "https://asiointi.starthealth.fi/",
      serviceArea: "Helsinki (paikan p\xE4\xE4ll\xE4) ja koko Suomi et\xE4vastaanotoin.",
      audience: "1\u2013200 hengen pk-yritykset ja startupit.",
      languages: ["fi", "en"]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "starthealth-mcp",
  title: "StartHealth MCP",
  version: "0.1.0",
  instructions: "Public tools for StartHealth, a modern occupational health provider for Finnish SMEs and startups. Use `list_service_packages` to see the Minimum/Basic/Support packages, `estimate_price` for a rough monthly price (low-exposure industries only), `list_articles` to browse Finnish occupational-health guides, and `get_contact_info` for contact and booking details.",
  tools: [list_service_packages_default, estimate_price_default, list_articles_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
